- name: show secret
  hosts: servers
  become: true
  vars_files:
    - secret.yml
  tasks:
    - name: show username
      debug:
        msg: "Username is {{ username }}"
    - name: show password
      debug:
        msg: "Password is {{ password }}"
    - name: show api_key
      debug:
        msg: "Api key is {{ api_key }}"